### PR TITLE
Fix/Readd layoutManager.closeProfileMenu

### LINKED ISSUE #269: Going to a new page via profileMenu does refresh application
### How to reproduce
1. Go the the website
2. Open the profile menu
3. Click on a link

### Expected behaviour
The page is loaded, and the profile menu is closed.

### Current behaviour
The full application refreshes. 

It seems to be related to a call to `layoutMananger.closeProfileMenu`, this method does not exists anymore. probably we have to change this call to `layoutManager.toggleProfileMenu`. 

Sentry: https://sentry.io/organizations/csvalpha/issues/2233600524/?project=186017&query=is%3Aunresolved

### PR DESCRIPTION
**Pull request by guidojw**
#260 removed the layoutManager.closeProfileMenu method. This PR makes the menu auto closing use the toggle method instead.

This PR resolves #269 
fixes AMBER-UI-PRODUCTION-XF

### CODE REVIEW

File: app/components/menu-sidebar-item.js [hunk 1]
```diff
@@ -6,8 +6,8 @@ const MenuSidebarItemComponent = Component.extend({
   minor: false,
   actions: {
     closeAfterNavigation() {
-      if (this.minor) {
-        this.layoutManager.closeProfileMenu();
+      if (this.minor && this.layoutManager.profileMenuOpen) {
```
Comment (Matthijsy) [inline app/components/menu-sidebar-item.js:9]: I know I suggested this myself, but maybe it is better to add the `closeProfileMenu` method again, since now we have to check the status of the profileMenu here before toggling, otherwise we do not have to care about the state of the service and just say close.

Comment (guidojw) [reply app/components/menu-sidebar-item.js:9]: Okay, I'll add it back 👍🏼

**Review by Matthijsy — APPROVED** [review]
