### PR TITLE
Fix activity consumption list

### LINKED ISSUE #325: Cannot show/print the "streeplijst"
### How to reproduce
1. Go towards an activity with some enrollments
2. Click on "print ingeschreven"
3. Click on "streeplijst"

### Expected behaviour
The list below should change to an "streeplijst" that can be printed

### Current behaviour
Nothing happens

### PR DESCRIPTION
**Pull request by wilco375**
### Summary
Fixes #325

### CODE REVIEW

File: app/components/form/consumption-list.js [hunk 1]
```diff
@@ -0,0 +1,12 @@
+import Component from '@ember/component';
+
+const ConsumptionListComponent = Component.extend({
```
Comment (Matthijsy) [inline app/components/form/consumption-list.js:3]: Could you write this component in the new octane style? Saves some migrations later

Comment (wilco375) [reply app/components/form/consumption-list.js:3]: Unfortunately this is not doable without updating a ton of other components too

**Review by DrumsnChocolate — APPROVED** [review]
