### PR TITLE
Fix photo sorting

### LINKED ISSUE #528: Wrong order of photos
### How to reproduce
1. Open a photo album
2. Open a photo
3. Click on the 'next' arrow to go to the next picture

### Expected behaviour
The next picture in chronological order is shown (as in the album)

### Current behaviour
The picture with the next ID is shown

### PR DESCRIPTION
**Pull request by wilco375**
Fixes #528

### CODE REVIEW

File: app/controllers/photo-albums/photo-album/photos/show.js [hunk 1]
```diff
@@ -4,7 +4,9 @@ import Controller from '@ember/controller';
 export default Controller.extend({
   session: service(),
   advanceToPhoto(delta) {
-    const photos = this.model.photoAlbum.get('photos');
+    const photos = this.model.photoAlbum
+      .get('photos')
+      .sortBy('exifDateTimeOriginal', 'createdAt');
```
Comment (DrumsnChocolate) [inline app/controllers/photo-albums/photo-album/photos/show.js:9]: can't this sorting take place in the `PhotoAlbum` model? For clarification, see `models/form/form.js`, specifically `get sortedQuestions()`.

File: app/routes/photo-albums/photo-album/photos/show.js [hunk 2]
```diff
@@ -11,7 +11,9 @@ export default class ShowPhotosRoute extends ApplicationRoute {
 
   get breadCrumb() {
     const photo = this.controller.model;
-    const allAlbumPhotos = this.controller.model.photoAlbum.get('photos');
+    const allAlbumPhotos = this.controller.model.photoAlbum
+      .get('photos')
+      .sortBy('exifDateTimeOriginal', 'createdAt');
```
Comment (DrumsnChocolate) [inline app/routes/photo-albums/photo-album/photos/show.js:16]: duplicate code, further support for my earlier comment

**Review by DrumsnChocolate — CHANGES_REQUESTED** [review]

**Review by guidojw — APPROVED** [review]
