### PR TITLE
Fix new forum post content resetting

### LINKED ISSUE #520: bug: text in the reageren box on the forum is not reset when visiting a different thread
### How to reproduce

1. Write something in the reageren box in a forum thread.
2. Navigate to a different forum thread using any buttons on the website (so don´t refresh the page or type the url yourself).
3. Look at the reageren box in that thread.

### Expected behaviour

When you look at the second visited forum thread, the reageren box should contain no text, as a user probably does not want to reuse their reaction text for the first thread in the second thread.

### Current behaviour

The text that was in the reageren box in the first thread is carried over to the reageren box in the second thread

### LINKED ISSUE #641: forum-post-new component does not clear contents upon cancel
brought up in https://github.com/csvalpha/amber-ui/pull/556#discussion_r996296640

### PR DESCRIPTION
**Pull request by Ellen-Wittingen**
fix #520 and fixes that the cancel button on the new forum post actually clears the content
fix #641

### CODE REVIEW

File: app/components/forum/forum-post-new.js [hunk 1]
```diff
@@ -25,6 +25,6 @@ export default class ForumPostNewComponent extends Component {
 
   @action
   cancel() {
-    this.content = '';
+    this.set('content', '');
```
Comment (guidojw) [inline app/components/forum/forum-post-new.js:28]: We have to consider that this is not "Octane style" and will give a lint error once https://github.com/csvalpha/amber-ui/blob/fca981602f54d818300d07c4b346b347b6c34f1d/.eslintrc.js#L30 is reenabled.

**Comment by DrumsnChocolate** [comment]
I've turned the ForumPostNew component into a glimmer component. I'm not sure why things were broken in the classic component, but I also don't want to bother with that, since this new implementation fixed the problem.
For reference, data binding is now one-way (that's a trait of glimmer components): https://guides.emberjs.com/release/upgrading/current-edition/glimmer-components/#toc_one-way-data-flow
This means the new component now modifies contents by calling a function passed in its arguments.

File: app/routes/forum/categories/category/threads/thread/posts/index.js [hunk 2]
```diff
@@ -68,6 +68,24 @@ export default class PostIndexRoute extends AuthenticatedRoute {
...
+          this.modelFor('forum.categories.category.threads.thread')?.id
+      )
+    ) {
+      const controller = this.controllerFor(routeName);
+      if (controller) {
+        controller.send('resetNewContent');
+      }
+    }
+  }
+
```
Comment (DrumsnChocolate) [inline app/routes/forum/categories/category/threads/thread/posts/index.js:88]: haven't touched this, will have a look at whether this is octane style

File: app/routes/forum/categories/category/threads/thread/posts/index.js [hunk 3]
```diff
@@ -68,6 +68,24 @@ export default class PostIndexRoute extends AuthenticatedRoute {
     this.controller.send('goToNextPage');
   }
 
+  @action
+  beforeModel(transition) {
+    const routeName = 'forum.categories.category.threads.thread.posts.index';
```
Comment (DrumsnChocolate) [inline app/routes/forum/categories/category/threads/thread/posts/index.js:73]: this is unnecessary. we can just use `this.routeName`

File: app/routes/forum/categories/category/threads/thread/posts/index.js (hunk 2 above)
Comment (DrumsnChocolate) [reply app/routes/forum/categories/category/threads/thread/posts/index.js]: I've simplified this.
see https://api.emberjs.com/ember/4.8/classes/Route/methods/resetController?anchor=resetController

File: app/routes/forum/categories/category/threads/thread/posts/index.js [hunk 4]
```diff
@@ -68,6 +68,13 @@ export default class PostIndexRoute extends AuthenticatedRoute {
     this.controller.send('goToNextPage');
   }
 
+  resetController(controller, isExiting, transition) {
```
Comment (DrumsnChocolate) [inline app/routes/forum/categories/category/threads/thread/posts/index.js:71]: https://api.emberjs.com/ember/4.8/classes/Route/methods/resetController?anchor=resetController for docs on this hook

**Review by DrumsnChocolate — APPROVED** [review]
it's a bit weird to approve my own changes

File: app/components/forum/forum-post-new.js [hunk 5]
```diff
@@ -9,20 +9,19 @@ export default class ForumPostNewComponent extends Component {
 
   @action
   async save() {
-    let { content, thread } = this;
```
Comment (wilco375) [inline app/components/forum/forum-post-new.js:12]: You could also update this line to `= this.args` instead of doing that in `createRecord` below; not sure what's more readable

**Review by wilco375 — APPROVED** [review]

**Comment by DrumsnChocolate** [comment]
see #657 for a silly extra PR that fixes the same thing. I forgot this PR existed, but apparently I solved it in a very similar manner. I added some small stuff added in #657 by merging the PR directly into this branch. See the comments on that PR for a detailed explanation.
> You could also update this line to = this.args instead of doing that in createRecord below; not sure what's more readable

This is now also taken care of.

File: app/controllers/forum/categories/category/threads/thread/posts/index.js [hunk 6]
```diff
@@ -55,8 +54,12 @@ export default class PostsIndexController extends Controller {
 
   @action
   async addQuote(q) {
-    this.set('newContent', `${this.newContent}${q} \n\n`);
-
+    if (!this.newContent?.endsWith('\n')) {
```
Comment (guidojw) [inline app/controllers/forum/categories/category/threads/thread/posts/index.js:57]: Unnecessary chaining :p, confused me because now it looks like `this.newContent` could be undefined/null and this conditional will pass then because !undefined/!null == true
